num1= input("请输入一个数:")
num1 = float(num1)
num2 = input("请输入一个数:")
num2 = float(num2)
print(f"两个数的和是: {num1 + num2}")
print(f"两个数的差是：{num1 - num2}")
print(f"两个数的积是：{num1 * num2}")
print(f"两个数的商是：{num1 / num2}")
print(type(num1))
print(type(num2))
print("Hello Github")
print("这是实验分支上的修改")